apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service
  namespace: nexflow
  labels:
    app: resource-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-service
  template:
    metadata:
      labels:
        app: resource-service
    spec:
      containers:
        - name: resource-service
          image: nexflow/resource-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: nexflow-config
                  key: NODE_ENV
            - name: MONGO_URI
              value: "mongodb://mongo-resource:27017/resource_db"
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: nexflow-config
                  key: RABBITMQ_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 8
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: nexflow
spec:
  selector:
    app: resource-service
  ports:
    - port: 3002
      targetPort: 3002
